spring.application.name=apigateway
server.port=8080

spring.cloud.gateway.server.webflux.routes[0].id=customer-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/customer/**

spring.cloud.gateway.server.webflux.routes[1].id=rider-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/rider/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webflux.routes[2].id=location-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/location/**

spring.cloud.gateway.server.webflux.routes[3].id=booking-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8084
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/booking/**

spring.cloud.gateway.server.webflux.routes[4].id=auth-service
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8085
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webflux.routes[5].id=payment-service
spring.cloud.gateway.server.webflux.routes[5].uri=http://localhost:8087
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/payment/**